### PR TITLE
Add CFLAGS and instruct nokogiri to use installer libraries.

### PR DESCRIPTION
**Pull request by chrisroberts**
Fixes mitchellh/vagrant#8594

### CODE REVIEW

**Comment by bdwyertech** [comment]
Wow, that was quick.  You da man! @chrisroberts

**Comment by legal90** [comment]
@chrisroberts Thanks!
Looking forward to a new Vagrant release with this fix included. 
Because currently our plugin `vagrant-parallels` is incompatible with Vagrant 1.9.5

**Comment by ggascoigne** [comment]
Can we please have a release that includes this fix?  The vagrant-vsphere plugin is also affected by this bug.

**Comment by chrisroberts** [comment]
@ggascoigne Yep, I am wrapping up some fixes on the Windows builds and once they are done a new release will be going out.

**Pull request merged**
