### PR TITLE
[ruby] Update Ruby version to 2.2.5

### PR DESCRIPTION
**Pull request by chrisroberts**
Fixes mitchellh/vagrant#7612

### CODE REVIEW

**Comment by sethvargo** [comment]
It looks like 2.3.1 is the latest - any reason not to do the full upgrade?

**Comment by chrisroberts** [comment]
Main reasoning being this is intended for a point release.

**Comment by sethvargo** [comment]
I just know there have been a bunch of upstream fixes for Ruby in Windows land, so I wonder if it makes sense bumping now. We have bumped in point releases before, and there are already a number of other "non-pointy" things in master, so I would just jump to latest. Keep in mind that we'll need to upgrade RubyEncoder for the plugin as well /cc @mitchellh

**Comment by chrisroberts** [comment]
:+1:

**Comment by mawatech** [comment]
I'm not sure if RubyEncoder is available for ruby versions > 2.2

**Comment by sethvargo** [comment]
Their website seems to say 2.2... Let's check that

**Comment by chrisroberts** [comment]
Going with latest 2.2 for now. Will revisit 2.3 next time.

**Pull request merged**
